### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by lchunleo** [Tinker-Twins/Python-Shared-Memory#1]
Given a setup that the writer is writing and the reader is reading the same shared memory. The writer or reader is suddenly stopped by killing the process. When either the writer or reader is up, can they able to continue with the same shared memory?

**Comment by Tinker-Twins** [comment]
Hi @lchunleo,

Killing `process2`, which latches to the shared memory, will have no effect on the shared memory buffer. The shared memory can still be accessed by any other process(es), including new ones, by passing in the correct `name` of the shared memory.
```python3
# Attach to a shared memory
shared_mem = SharedMemory(name='MyMemory', create=False)
```

However, killing `process1`, which creates the shared memory, will have either of the following consequences:
- If the shared memory is `closed` and `unlinked`, it will be destroyed.
    ```python3
    # Close access to the shared memory
    shared_mem.close()
    # Destroy the shared memory
    shared_mem.unlink()
    ```
- If the shared memory is **NOT** `closed` and `unlinked`, it will cached but may not be accessible by the same name (since the `name` variable would be lost after killing the script. This may have undesirable consequences!

Hope this helps!
